### ISSUE TITLE
dimensions of stacks

### ISSUE THREAD

**Issue by wwieder** [piersond/MIMICS_HiRes#2]
https://github.com/piersond/MIMICS_HiRes/blob/24b6fc2b2bf853ab9d7d784726e5d65c9512fa9e/Figures/Fig6_Scenario%20maps/RC_mapGPP10_mn_sd_total-change.R#L30

what are the dimensions of these variables.  I'd assume that you want to calculate the change in SOC from 'initial' SOC for each parameter set (e.g., both data are dimensioned lat x lon x ensemble member)

**Comment by piersond** [comment]
The estSOC_stack is composed of the 30 ensemble rasters, each aligned at the cellular level. The code here is aligning and subtracting the default (i.e. no scenario) ensemble mean SOC raster from each raster in the stack.

If I'm interpreting your last comment correctly, you're suggesting that I should subtract the default SOC raster from the scenario raster for each specific ensemble (i.e. calc the diff first, not stack first). Then stack those rasters and perform the mean and std dev calculation?

**Comment by piersond** [comment]
Here's the result if I calculate the difference for each ensemble pair, then stack and calc mean and stdev of the difference. Big difference! Thanks for your help with this. 

![image](https://user-images.githubusercontent.com/36753480/136097221-4ae7ae2b-2d6d-4e7a-a2c1-c452c596d13e.png)

**Comment by wwieder** [comment]
Yep, calculate the difference first and then calculate the mean and SD from
those 'raw' data.

**Comment by wwieder** [comment]
the magnitude of the SD makes more sense, relative to the means.
